FROM ubuntu:20.10

RUN sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y build-essential wget zlib1g-dev libssl-dev libedit-dev

WORKDIR /build

RUN wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-8.3p1.tar.gz && \
    tar xzf openssh-8.3p1.tar.gz && mv openssh-8.3p1 openssh

WORKDIR /build/openssh

RUN sed -i 's/#define SSH_VERSION.*/#define SSH_VERSION "OpenSSH_?"/' version.h

RUN ./configure --prefix=/usr/local && make -j$(nproc) && cp ssh /usr/local/bin/

LABEL name="C3_V2"